name: Push actions

on:
  push:
    branches:
      - main
      - dev

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
      - uses: "actions/checkout@v3.3.0"

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: brands

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v3.3.0"

        - name: "Set up Python"
          uses: actions/setup-python@v4.5.0
          with:
            python-version: "3.10"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements.txt

        - name: "Run"
          run: python3 -m ruff check .

  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v3.3.0"
      - name: Setup Python
        uses: "actions/setup-python@v4.5.0"
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python3 -m pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            -n auto \
            --cov custom_components.stiebel_eltron_isg \
            -o console_output_style=count \
            -p no:sugar \
            tests
